from __future__ import annotations

EMPTY_SLOT_STATUS = "EMPTY"
ACTIVE_SLOT_STATUS = "ACTIVE"
DELETED_SLOT_STATUS = "DELETED"

DEFAULT_BASE_ADDRESS = 0
DEFAULT_INITIAL_CAPACITY = 23
DEFAULT_MAX_LOAD_FACTOR = 0.70
DEFAULT_REHASH_OCCUPANCY_FACTOR = 0.90

CAPACITY_GROWTH_FACTOR = 2
CAPACITY_GROWTH_OFFSET = 1

RUSSIAN_ALPHABET = tuple("АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ")
ENGLISH_ALPHABET = tuple("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

RUSSIAN_ALPHABET_NAME = "RU"
ENGLISH_ALPHABET_NAME = "EN"

RUSSIAN_ALPHABET_BASE = len(RUSSIAN_ALPHABET)
ENGLISH_ALPHABET_BASE = len(ENGLISH_ALPHABET)

MENU_CREATE_OPTION = "1"
MENU_READ_OPTION = "2"
MENU_UPDATE_OPTION = "3"
MENU_DELETE_OPTION = "4"
MENU_PRINT_OPTION = "5"
MENU_STATS_OPTION = "6"
MENU_EXIT_OPTION = "0"

MENU_TEXT = (
    "\nHash table menu:\n"
    "1. Create\n"
    "2. Read\n"
    "3. Update\n"
    "4. Delete\n"
    "5. Print table\n"
    "6. Show stats\n"
    "0. Exit"
)
