BIT_COUNT = 32
ZERO_BIT = 0
ONE_BIT = 1

ALLOWED_BITS = {ZERO_BIT, ONE_BIT}

FRACTION_PRECISION = 5
FRACTION_LIMIT = 50

SIGN_BITS = 1
INTEGER_BITS = BIT_COUNT - SIGN_BITS - FRACTION_PRECISION

BCD_DECAD_SIZE = 4
MAX_DECAD_POWER = 3

MANTISSA_SIZE = 23
BASE_BIAS = 127

EXPONENT_BITS = 8
EXPONENT_START = SIGN_BITS
MANTISSA_START = SIGN_BITS + EXPONENT_BITS

DIGIT_SUM_LIMIT = 10
DECIMAL_BASE = 10